version: '3.3'
services:
  example-service:
    build:
      context: ./
    ports:
      - 3001:3000
      - 9001:9229
    command: npm run start:debug
    volumes:
      - ./src:/app/src:z
    env_file:
      - .env.example
    depends_on:
      - pubsub-service
    networks:
      - example-network
  pubsub-service:
    image: singularities/pubsub-emulator
    ports:
      - 8432:8432
    volumes:
    - dbdata:/opt/data # todo fix persist i am not sure needed
    environment:
       PUBSUB_LISTEN_ADDRESS: 0.0.0.0:8432
       PUBSUB_PROJECT_ID: example-project-id
    networks:
      - example-network
  pubsub-seed:
    build:
      context: ./
    depends_on:
      - pubsub-service
    command: npm run seed:pubsub -- init # can change values
    networks:
      - example-network
networks:
  example-network:
    external:
      name: example-network
volumes:
  dbdata:
